// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaProject_API.Infra.Context;

namespace WaProject_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210429005349_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WaProject_API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDaEntregaRealizada")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("EnderecoEntregaRealizada")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Pedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataDaEntregaRealizada = new DateTime(2021, 4, 30, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(1522),
                            DataDeCriacao = new DateTime(2021, 4, 28, 21, 53, 48, 623, DateTimeKind.Local).AddTicks(9),
                            EnderecoEntregaRealizada = "Rua 2, Numero 133, Sao Paulo"
                        },
                        new
                        {
                            Id = 2,
                            DataDaEntregaRealizada = new DateTime(2021, 4, 30, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4477),
                            DataDeCriacao = new DateTime(2021, 4, 29, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4429),
                            EnderecoEntregaRealizada = "Rua 18, Numero 135, Sao Paulo"
                        },
                        new
                        {
                            Id = 3,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 1, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4537),
                            DataDeCriacao = new DateTime(2021, 4, 30, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4534),
                            EnderecoEntregaRealizada = "Rua 13, Numero 154, Sao Paulo"
                        },
                        new
                        {
                            Id = 4,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 2, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4550),
                            DataDeCriacao = new DateTime(2021, 5, 1, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4548),
                            EnderecoEntregaRealizada = "Rua 6, Numero 152, Sao Paulo"
                        },
                        new
                        {
                            Id = 5,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 3, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4560),
                            DataDeCriacao = new DateTime(2021, 5, 2, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4558),
                            EnderecoEntregaRealizada = "Rua 7, Numero 148, Sao Paulo"
                        },
                        new
                        {
                            Id = 6,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 4, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4569),
                            DataDeCriacao = new DateTime(2021, 5, 3, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4567),
                            EnderecoEntregaRealizada = "Rua 3, Numero 148, Sao Paulo"
                        },
                        new
                        {
                            Id = 7,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 5, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5001),
                            DataDeCriacao = new DateTime(2021, 5, 4, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(4994),
                            EnderecoEntregaRealizada = "Rua 14, Numero 71, Sao Paulo"
                        },
                        new
                        {
                            Id = 8,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 6, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5013),
                            DataDeCriacao = new DateTime(2021, 5, 5, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5011),
                            EnderecoEntregaRealizada = "Rua 1, Numero 186, Sao Paulo"
                        },
                        new
                        {
                            Id = 9,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 7, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5022),
                            DataDeCriacao = new DateTime(2021, 5, 6, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5021),
                            EnderecoEntregaRealizada = "Rua 6, Numero 107, Sao Paulo"
                        },
                        new
                        {
                            Id = 10,
                            DataDaEntregaRealizada = new DateTime(2021, 5, 8, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5031),
                            DataDeCriacao = new DateTime(2021, 5, 7, 21, 53, 48, 626, DateTimeKind.Local).AddTicks(5030),
                            EnderecoEntregaRealizada = "Rua 3, Numero 160, Sao Paulo"
                        });
                });

            modelBuilder.Entity("WaProject_API.ValueObjects.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Equipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Equipe Cod - 6801 atendimento especial",
                            Nome = "Equipe Setor - 42",
                            PedidoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Equipe Cod - 7638 atendimento especial",
                            Nome = "Equipe Setor - 47",
                            PedidoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Equipe Cod - 5520 atendimento especial",
                            Nome = "Equipe Setor - 42",
                            PedidoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Equipe Cod - 3742 atendimento especial",
                            Nome = "Equipe Setor - 45",
                            PedidoId = 4
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Equipe Cod - 6294 atendimento especial",
                            Nome = "Equipe Setor - 45",
                            PedidoId = 5
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Equipe Cod - 4494 atendimento especial",
                            Nome = "Equipe Setor - 41",
                            PedidoId = 6
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Equipe Cod - 2867 atendimento especial",
                            Nome = "Equipe Setor - 49",
                            PedidoId = 7
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Equipe Cod - 4120 atendimento especial",
                            Nome = "Equipe Setor - 43",
                            PedidoId = 8
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Equipe Cod - 4101 atendimento especial",
                            Nome = "Equipe Setor - 46",
                            PedidoId = 9
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Equipe Cod - 7993 atendimento especial",
                            Nome = "Equipe Setor - 48",
                            PedidoId = 10
                        });
                });

            modelBuilder.Entity("WaProject_API.ValueObjects.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Tv LED Cod - 3279 Samsung",
                            Nome = "Tv LED Cod - 47",
                            PedidoId = 1,
                            Valor = 1345m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Tv LED Cod - 8254 Samsung",
                            Nome = "Tv LED Cod - 41",
                            PedidoId = 1,
                            Valor = 1245m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Tv LED Cod - 3978 Samsung",
                            Nome = "Tv LED Cod - 49",
                            PedidoId = 2,
                            Valor = 1376m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Tv LED Cod - 2446 Samsung",
                            Nome = "Tv LED Cod - 41",
                            PedidoId = 2,
                            Valor = 1692m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Tv LED Cod - 3195 Samsung",
                            Nome = "Tv LED Cod - 48",
                            PedidoId = 3,
                            Valor = 1239m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Tv LED Cod - 7515 Samsung",
                            Nome = "Tv LED Cod - 43",
                            PedidoId = 3,
                            Valor = 1107m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Tv LED Cod - 3089 Samsung",
                            Nome = "Tv LED Cod - 43",
                            PedidoId = 4,
                            Valor = 1120m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Tv LED Cod - 3136 Samsung",
                            Nome = "Tv LED Cod - 40",
                            PedidoId = 4,
                            Valor = 1710m
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Tv LED Cod - 7509 Samsung",
                            Nome = "Tv LED Cod - 45",
                            PedidoId = 5,
                            Valor = 1744m
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Tv LED Cod - 7440 Samsung",
                            Nome = "Tv LED Cod - 45",
                            PedidoId = 5,
                            Valor = 1737m
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Tv LED Cod - 8847 Samsung",
                            Nome = "Tv LED Cod - 42",
                            PedidoId = 6,
                            Valor = 1573m
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Tv LED Cod - 2121 Samsung",
                            Nome = "Tv LED Cod - 42",
                            PedidoId = 6,
                            Valor = 1045m
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Tv LED Cod - 6244 Samsung",
                            Nome = "Tv LED Cod - 43",
                            PedidoId = 7,
                            Valor = 1911m
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Tv LED Cod - 6153 Samsung",
                            Nome = "Tv LED Cod - 49",
                            PedidoId = 7,
                            Valor = 1292m
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Tv LED Cod - 4785 Samsung",
                            Nome = "Tv LED Cod - 48",
                            PedidoId = 7,
                            Valor = 1549m
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Tv LED Cod - 5256 Samsung",
                            Nome = "Tv LED Cod - 44",
                            PedidoId = 8,
                            Valor = 1741m
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Tv LED Cod - 8907 Samsung",
                            Nome = "Tv LED Cod - 48",
                            PedidoId = 9,
                            Valor = 1514m
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Tv LED Cod - 8583 Samsung",
                            Nome = "Tv LED Cod - 45",
                            PedidoId = 10,
                            Valor = 1651m
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Tv LED Cod - 6602 Samsung",
                            Nome = "Tv LED Cod - 47",
                            PedidoId = 10,
                            Valor = 1020m
                        });
                });

            modelBuilder.Entity("WaProject_API.ValueObjects.Equipe", b =>
                {
                    b.HasOne("WaProject_API.Models.Pedido", null)
                        .WithOne("Equipe")
                        .HasForeignKey("WaProject_API.ValueObjects.Equipe", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WaProject_API.ValueObjects.Produto", b =>
                {
                    b.HasOne("WaProject_API.Models.Pedido", null)
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
